### ISSUE TITLE
DataGrid bug with 0.9.4

### ISSUE THREAD

**Issue by robalexclark** [Megabit/Blazorise#2658]
I just upgraded from 0.9.3 preview 5 to 0.9.4, and get a nasty null reference exception on load:

 ```
   <app>
        <component type="typeof(App)" render-mode="ServerPrerendered" />
    </app>
```

I'm trying to figure it out by stripping back the razor and code but no luck yet other than it probably is something to do with the datagrid virtualize stuff. 

Even a plain grid like:

```
<DataGrid  TItem="Animal"  >
</DataGrid>
```

causes it, so not sure where to look next...

Just letting you know and I'll keep looking tomorrow

**Comment by stsrki** [comment]
Are you sure have all the required JS files? Did you cleared the cache?

**Comment by David-Moreira** [comment]
Do take a look at your console and let us know the error you're getting. Either way the most likely issue as strski mentioned is cache.

However if you can find the steps to reproduce it, on a separate repository we can take a detailed look at it.

**Comment by ehsangfl** [comment]
error message
```
rit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100] Unhandled exception rendering component: Value cannot be null. (Parameter 'source')
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.ToList[Tbl_CNT_Person](IEnumerable`1 source)
at Blazorise.DataGrid.DataGrid`1[[AppModel.Web.Model.Tbl_CNT_Person, Sayeh.AppModel, Version=1.0.0.2, Culture=neutral, PublicKeyToken=null]].<BuildRenderTree>b__492_5(RenderTreeBuilder __builder4)
```

**Comment by robalexclark** [comment]
Cleared my cache :-)

Yes @ehsangfl does seem to be something to do with a null datasource as wrapping the datagrid in a null check fixes it. Its happening on more than one datagrid, so probably for all datagrids we might need to do a null check?

Haven't quite bottomed it out yet though so will keep looking....

**Comment by stsrki** [comment]
If the null is making a problem we should definitely fix it and release a patch.

**Comment by robalexclark** [comment]
Tried about 5-6 datagrids now and they all show the same problem, ones that appear on the initial screen through an error at:
```
  <app>
       <component type="typeof(App)" render-mode="ServerPrerendered" />
   </app>
```

but after I fix those with a null check and navigate to other pages with grids, even simple grids show an error in the console:
```

System.NullReferenceException: Object reference not set to an instance of an object.
   at Blazorise.DataGrid.DataGrid`1.<BuildRenderTree>b__492_5(RenderTreeBuilder __builder4)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at Blazorise.TableBody.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit 'lcCoSVVo6vW8Dw7MLjIh-CVEOagr2eCPFaA2UjmtE7Y'.

System.NullReferenceException: Object reference not set to an instance of an object.
   at Blazorise.DataGrid.DataGrid`1.<BuildRenderTree>b__492_5(RenderTreeBuilder __builder4)
   at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.AddContent(Int32 sequence, RenderFragment fragment)
   at Blazorise.TableBody.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

and as before a @if(mydata !=null). fixes it.

**Comment by ehsangfl** [comment]
@robalexclark I never use third party direct in my apps. usually I use a class inherited from third party class.in this item, I check null in inherited class and all of the forms working properly. In this way, you can change your third party without changing your forms

**Comment by David-Moreira** [comment]
Hello guys,
Thanks for reporting this issue, we'll patch it as soon as possible.

**Comment by stsrki** [comment]
I cannot reproduce the error. I've set the `Data` to null, and remove the `Data` parameter from `DataGrid`. Tried the WebAssemply and Server project, in both Server and ServerPrerendered modes. And I still cannot make it to raise an error.

**Comment by stsrki** [comment]
So, I was able to reproduce it and seems that @David-Moreira fixed it with #2659. I also added another check for null value just in case. Tomorrow we'll release a patch.

**Comment by sturlath** [comment]
I´m hitting this right now **but** only if I ctrl+F5 where debug mode (F5) works fine. I have no #if debug stuff that is bringing in extra data..

I was not trying to get data in `OnInitializedAsync()`, only in DataGrid properties `Data="myData" ReadData="OnDataGridReadAsync"`

When I added `@if(myData !=null)` and fetch the data in `OnInitializedAsync()` things work as they should.


I´m using 0.9.4.3

**Comment by robalexclark** [comment]
So the difference I am seeing is that you are using ReadData - if you take that out does it work?
