### ISSUE TITLE
0.9.4 RichTextEdit gives exceptions

### ISSUE THREAD

**Issue by njannink** [Megabit/Blazorise#2717]
I updated to 0.9.4 and now exceptions appear in the chrome console:

```
Uncaught (in promise) Error: System.ArgumentException: The type 'RichTextEdit' does not contain a public invokable method with [JSInvokableAttribute("")].
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.GetCachedMethodInfo(IDotNetObjectReference objectReference, String methodIdentifier)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet(JSRuntime jsRuntime, DotNetInvocationInfo invocationInfo, String argsJson)
    at Object.endInvokeDotNetFromJS (blazor.webassembly.js?version=5.0.1:1)
    at Object.invokeJSFromDotNet (blazor.webassembly.js?version=5.0.1:1)
    at Object.w [as invokeJSFromDotNet] (blazor.webassembly.js?version=5.0.1:1)
    at _mono_wasm_invoke_js_blazor (dotnet.5.0.8.js:1)
    at do_icall (<anonymous>:wasm-function[10596]:0x194e4e)
    at do_icall_wrapper (<anonymous>:wasm-function[3305]:0x79df9)
    at interp_exec_method (<anonymous>:wasm-function[2155]:0x44ad3)
    at interp_runtime_invoke (<anonymous>:wasm-function[7862]:0x12efff)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[7347]:0x118e5f)
    at do_runtime_invoke (<anonymous>:wasm-function[3304]:0x79d42)
```

Even when I use a plain `<RichTextEdit />` I see these exceptions being logged. The weird thing is that if works normally further. Only these exceptions are polluting my console window. I tried to find the cause of this, but I'm kinda stuck. Also the demo projects of Blazorise don't have these issues. @stsrki maybe you got any ideas or directions to look at?

**Comment by njannink** [comment]
I actually found what it is. In my case the QuillJS javascript file was loaded twice, because I forgot to remove the direct link. This was causing the above side-effect. Totally unrelated.

Anyway problem solved
