### ISSUE TITLE
NumericEdit does not support Byte with Step-buttons

### ISSUE THREAD

**Issue by StefanOssendorf** [Megabit/Blazorise#2772]
**Describe the bug**
Using `Byte` as `TValue` causes an exception when using the step-buttons.

**To Reproduce**
```csharp
<NumericEdit TValue="Byte" Step="1" EnableStep="true" ShowStepButtons="true" />
```
1. Add this to any Blazorise-enabled project
2. Use the buttons shown in the textbox on the page
3. The typical "blazor error pane" is shown

Console error log:
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Specified cast is not valid.
System.InvalidCastException: Specified cast is not valid.
   at Blazorise.Utilities.Converters.ChangeType[Byte](Object value)
   at Blazorise.NumericEdit`1[[System.Byte, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].AddStep(Byte value, Int32 sign)
   at Blazorise.NumericEdit`1[[System.Byte, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnSpinDownClicked()
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[Object](MulticastDelegate delegate, Object arg)
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync(Object arg)
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
   at Microsoft.AspNetCore.Components.EventCallback.InvokeAsync(Object arg)
   at Blazorise.Button.ClickHandler()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

**Expected behavior**
The value should be increased or decreased as given by the `Step` value.

**Additional context**
Blazorise v0.9.4.2

**Comment by StefanOssendorf** [comment]
I did a bit of source code digging and found the following:
The "problem" is this line within the `NumericEdit.AddStep()` method.
This `Converters.ChangeType<TValue>( Step.GetValueOrDefault( 1 ) * sign )` does not work for a `Byte` with a domain of (0..255) because `sign` has the value of `-1` due to subtraction.
Changing this line into something like this:
```csharp
Func<TValue, TValue, TValue> operation;
if (sign > 0)
{
    operation = MathUtils<TValue>.Add;
}
else
{
    operation = MathUtils<TValue>.Subtract;
}

return operation(value, Converters.ChangeType<TValue>(step));
```
Get's me into the `MathUtils` class where I get another exception. The exception is
```
System.InvalidOperationException: 'The binary operator Subtract is not defined for the types 'System.Byte' and 'System.Byte'.'
```
What got me thinking. After some googlefu and StackOverflow it seems that the `byte` data type does not define an addition or subtraction operator in the form of: `byte = byte OP byte` but _always_ `int = byte OP byte`.
With that found out I think I should change my code to use an integer and make sure I stay within the byte range of 0..255.
But if you say you want to implement that this works, I won't say no ;-)

Feel free to close this if you decide it as a "Won't fix".

**Comment by stsrki** [comment]
Not sure really if I would want to add specific overloads for `byte` types. It's really an edge case. And you can always _workaround_ it with an `int` field and then cast it in your app to `byte`. Like you already did.

So I think it's best to close the ticket.

**Comment by StefanOssendorf** [comment]
Yeah. But this applies to all unsigned types. But I don't know if that
would change the outcome. Just so you are aware of it

Mladen Macanović ***@***.***> schrieb am Sa., 7. Aug. 2021,
12:26:
