### ISSUE TITLE
Modal Error - Cannot read property 'style' of null at Object.resetAdjustments

### ISSUE THREAD

**Issue by tommykri** [Megabit/Blazorise#2779]
**Describe the bug**
When I want to dynamically show/hide a modal dialog entirely based on user interaction where the modal is removed from HTML markup when not open I get an error when closing the modal from a button click inside of the modal.

If you click outside of the modal to close it, there are no errors.

**To Reproduce**
Use this code:

```
<Button Clicked="() => Visible = true">
    Show dialog
</Button>

@if (Visible)
{
    <Modal Visible="true">
        <ModalContent>
            <ModalBody>
                <Button Clicked="() => Visible = false">
                    Hide dialog
                </Button>
            </ModalBody>
        </ModalContent>
    </Modal>
}

@code
{
    public bool Visible { get; set; }
}
```

1. Click on 'Show dialog'
2. Click on 'Hide dialog'
3. See error:
Error: Microsoft.JSInterop.JSException: Cannot read property 'style' of null
TypeError: Cannot read property 'style' of null
    at Object.resetAdjustments (https://localhost:44368/_content/Blazorise.Bootstrap/blazorise.bootstrap.js?v=0.9.4.2:64:21)
    at Object.close (https://localhost:44368/_content/Blazorise.Bootstrap/blazorise.bootstrap.js?v=0.9.4.2:48:45)
    at https://localhost:44368/_framework/blazor.server.js:1:70368
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:44368/_framework/blazor.server.js:1:70334)
    at https://localhost:44368/_framework/blazor.server.js:1:26441
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:44368/_framework/blazor.server.js:1:26411)
    at e.processIncomingData (https://localhost:44368/_framework/blazor.server.js:1:24222)
    at e.connection.onreceive (https://localhost:44368/_framework/blazor.server.js:1:17307)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Blazorise.Modal.DisposeAsync(Boolean disposing)
   at Blazorise.BaseAfterRenderComponent.DisposeAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<RenderInExistingBatch>g__GetHandledAsynchronousDisposalErrorsTask|48_0(Task result)

Error thrown because element is NULL on this line:
https://github.com/Megabit/Blazorise/blob/bfc1c3975e907ec9d0d781e98f5c58ea86a3d924/Source/Blazorise.Bootstrap/wwwroot/blazorise.bootstrap.js#L64

**Comment by StefanOssendorf** [comment]
I think you are using the modal not the way it's inteded to be used.
According to doc you should (must?) use a the following apporach:
```csharp
 private Modal modalRef;

    private void ShowModal()
    {
        modalRef.Show();
    }

    private void HideModal()
    {
        modalRef.Hide();
    }
```

**Comment by stsrki** [comment]
The recommended way is to always have Modal in the DOM but it's not a requirement. So this error is definitely a bug. Thanks for the report and the way to reproduce it?

**Comment by tommykri** [comment]
We encountered this issue in a list where each item has it's own Modal with dynamic content so we wanted it to completely go away from the DOM when we close the modal, to not have unnecessary modals in the DOM. I might refactor this to always have a single Modal in the DOM where content changes based on the selected item, but that requires some work. Nice to see a fix for this. Thanks for a quick response!
