### ISSUE TITLE
Unhandled exception rendering component: Could not find 'blazorise.tooltip.updateContent'

### ISSUE THREAD

**Issue by sturlath** [Megabit/Blazorise#2807]
Hi

I just updated all (abp.io also) my code and Blazorise to 0.9.4.3 and am hitting this error.

I have cleared all browser storage and run in private mode so nothing is cached.

There are two errors (one using VS 2022 and the other VS2019)

Am I missing any update steps?

```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'blazorise.tooltip.updateContent' ('updateContent' was undefined).
      Error: Could not find 'blazorise.tooltip.updateContent' ('updateContent' was undefined).
          at https://localhost:44307/global.js?_v=637598757568998193:54:1287
          at Array.forEach (<anonymous>)
          at e.findFunction (https://localhost:44307/global.js?_v=637598757568998193:54:1247)
          at b (https://localhost:44307/global.js?_v=637598757568998193:54:2989)
          at https://localhost:44307/global.js?_v=637598757568998193:54:3935
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://localhost:44307/global.js?_v=637598757568998193:54:3908)
          at Object.w [as invokeJSFromDotNet] (https://localhost:44307/global.js?_v=637598757568998193:54:64232)
          at _mono_wasm_invoke_js_blazor (https://localhost:44307/_framework/dotnet.6.0.0-preview.7.21377.19.js:1:190800)
          at do_icall (<anonymous>:wasm-function[10596]:0x194e4e)
Microsoft.JSInterop.JSException: Could not find 'blazorise.tooltip.updateContent' ('updateContent' was undefined).
Error: Could not find 'blazorise.tooltip.updateContent' ('updateContent' was undefined).
    at https://localhost:44307/global.js?_v=637598757568998193:54:1287
    at Array.forEach (<anonymous>)
    at e.findFunction (https://localhost:44307/global.js?_v=637598757568998193:54:1247)
    at b (https://localhost:44307/global.js?_v=637598757568998193:54:2989)
    at https://localhost:44307/global.js?_v=637598757568998193:54:3935
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://localhost:44307/global.js?_v=637598757568998193:54:3908)
    at Object.w [as invokeJSFromDotNet] (https://localhost:44307/global.js?_v=637598757568998193:54:64232)
    at _mono_wasm_invoke_js_blazor (https://localhost:44307/_framework/dotnet.6.0.0-preview.7.21377.19.js:1:190800)
    at do_icall (<anonymous>:wasm-function[10596]:0x194e4e)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__15`1[[System.Object, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Blazorise.Tooltip.<>c__DisplayClass9_0.<<SetParametersAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Blazorise.BaseAfterRenderComponent.OnAfterRenderAsync(Boolean firstRender)
   at Blazorise.BaseComponent.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

I´m also getting this version

```
 Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'blazorise.tooltip.destroy' ('destroy' was undefined).
      Error: Could not find 'blazorise.tooltip.destroy' ('destroy' was undefined).
          at https://localhost:44307/global.js?_v=637598757568998193:54:1287
          at Array.forEach (<anonymous>)
          at e.findFunction (https://localhost:44307/global.js?_v=637598757568998193:54:1247)
          at b (https://localhost:44307/global.js?_v=637598757568998193:54:2989)
          at https://localhost:44307/global.js?_v=637598757568998193:54:3935
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://localhost:44307/global.js?_v=637598757568998193:54:3908)
          at Object.w [as invokeJSFromDotNet] (https://localhost:44307/global.js?_v=637598757568998193:54:64232)
          at _mono_wasm_invoke_js_blazor (https://localhost:44307/_framework/dotnet.5.0.9.js:1:190800)
          at do_icall (<anonymous>:wasm-function[10596]:0x194e4e)
Microsoft.JSInterop.JSException: Could not find 'blazorise.tooltip.destroy' ('destroy' was undefined).
Error: Could not find 'blazorise.tooltip.destroy' ('destroy' was undefined).
    at https://localhost:44307/global.js?_v=637598757568998193:54:1287
    at Array.forEach (<anonymous>)
    at e.findFunction (https://localhost:44307/global.js?_v=637598757568998193:54:1247)
    at b (https://localhost:44307/global.js?_v=637598757568998193:54:2989)
    at https://localhost:44307/global.js?_v=637598757568998193:54:3935
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://localhost:44307/global.js?_v=637598757568998193:54:3908)
    at Object.w [as invokeJSFromDotNet] (https://localhost:44307/global.js?_v=637598757568998193:54:64232)
    at _mono_wasm_invoke_js_blazor (https://localhost:44307/_framework/dotnet.5.0.9.js:1:190800)
    at do_icall (<anonymous>:wasm-function[10596]:0x194e4e)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__15`1[[System.Object, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Blazorise.Tooltip.DisposeAsync(Boolean disposing)
   at Blazorise.BaseAfterRenderComponent.DisposeAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<RenderInExistingBatch>g__GetHandledAsynchronousDisposalErrorsTask|48_0(Task result)
```

**Comment by stsrki** [comment]
It might be ABP `global.js` is bundled with an older version of Blazorise javascript files.

**Comment by sturlath** [comment]
Ok thanks!! That led me to fix it 

I ran the [bundling tool](https://docs.abp.io/en/abp/latest/UI/Blazor/Global-Scripts-Styles) and it updated the global.js and global.css. I don't know why the `abp update` command didn't do that..

There is this warning `"Unable to minify the file: AuthenticationService.js. Adding file to the bundle without minification."` though. 
![image](https://user-images.githubusercontent.com/2386572/129200015-d1107323-ec3a-4c20-a0e2-16a0bccc6122.png)
