### ISSUE TITLE
Blazorise Tooltip Content Error - Could not find 'blazorise.tooltip.updateContent' 

### ISSUE THREAD

**Issue by davidjhurtado** [Megabit/Blazorise#2811]
I update to **abp.io 4.4.0** version.
And  Blazorise version is **0.9.4.1**

**I now i get and error.**
global.js?_v=637453969261716221:792 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'blazorise.tooltip.updateContent' ('updateContent' was undefined).
      Error: Could not find 'blazorise.tooltip.updateContent' ('updateContent' was undefined).
          at https://localhost:44307/global.js?_v=637453969261716221:792:1287
          at Array.forEach (<anonymous>)
          at e.findFunction (https://localhost:44307/global.js?_v=637453969261716221:792:1247)
          at b (https://localhost:44307/global.js?_v=637453969261716221:792:2989)
          at https://localhost:44307/global.js?_v=637453969261716221:792:3935
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://localhost:44307/global.js?_v=637453969261716221:792:3908)
          at Object.w [as invokeJSFromDotNet] (https://localhost:44307/global.js?_v=637453969261716221:792:64218)
          at _mono_wasm_invoke_js_blazor (https://localhost:44307/_framework/dotnet.5.0.9.js:1:190800)
          at do_icall (<anonymous>:wasm-function[10596]:0x194e4e)
Microsoft.JSInterop.JSException: Could not find 'blazorise.tooltip.updateContent' ('updateContent' was undefined).
Error: Could not find 'blazorise.tooltip.updateContent' ('updateContent' was undefined).
    at https://localhost:44307/global.js?_v=637453969261716221:792:1287
    at Array.forEach (<anonymous>)
    at e.findFunction (https://localhost:44307/global.js?_v=637453969261716221:792:1247)
    at b (https://localhost:44307/global.js?_v=637453969261716221:792:2989)
    at https://localhost:44307/global.js?_v=637453969261716221:792:3935
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://localhost:44307/global.js?_v=637453969261716221:792:3908)
    at Object.w [as invokeJSFromDotNet] (https://localhost:44307/global.js?_v=637453969261716221:792:64218)
    at _mono_wasm_invoke_js_blazor (https://localhost:44307/_framework/dotnet.5.0.9.js:1:190800)
    at do_icall (<anonymous>:wasm-function[10596]:0x194e4e)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__15`1[[System.Object, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Blazorise.Tooltip.<>c__DisplayClass9_0.<<SetParametersAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Blazorise.BaseAfterRenderComponent.OnAfterRenderAsync(Boolean firstRender)
   at Blazorise.BaseComponent.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

**Example of code**
```
<Blazorise.Row>
    <Blazorise.Column>
        @L["Customer"]
    </Blazorise.Column>
    <Blazorise.Column>
        <Blazorise.Tooltip Text="@MessageForOpenTicketsByCustomer" Placement="TooltipPlacement.Bottom" Multiline="false"> <Badge Color="Color.Warning">  @L["OpenMessage"] <Badge Color="Color.Light"> @TotalOpenTicketsByCustomer</Badge></Badge></Blazorise.Tooltip>
    </Blazorise.Column>
</Blazorise.Row>
```
**Expected behavior**
When i was on abp.io version 4.2.1 and Blazorise version _0.9.3-preview6_ we didn't get that error.

**Screenshots**
![image](https://user-images.githubusercontent.com/13089183/129426441-7a469873-e442-41ea-b369-e47c75559843.png)

**Additional context**
We are using Blazor Web Assembly

**Comment by stsrki** [comment]
Probably the same problem as #2807

You need to run [bundling tool](https://docs.abp.io/en/abp/latest/UI/Blazor/Global-Scripts-Styles)

**Comment by davidjhurtado** [comment]
Thanks a lot. It's **solve** the situation.

**Comment by sturlath** [comment]
@davidjhurtado did you not get the following warning as I did?
`"Unable to minify the file: AuthenticationService.js. Adding file to the bundle without minification."`

I added this to the [4.4.0 bug report](https://support.abp.io/QA/Questions/1543/Bugs--Issues-v44X#answer-188d99ae-9ac8-ed8b-2663-39fe57b118e6) since we are two that had this issue.

**Comment by davidjhurtado** [comment]
Yes, I  got it.
`[08:41:46 WRN] Unable to minify the file: AuthenticationService.js. Adding file to the bundle without minification.`
