### ISSUE TITLE
RichTextEdit: System.InvalidOperationException

### ISSUE THREAD

**Issue by stevenlupo** [Megabit/Blazorise#3014]
Were there any breaking changes in the `RichTextEdit`? I hadn't made any changes to the page and it broke for no reason that I can see. I did upgrade Blazorise though, using 0.9.4.6.

```
blazor.server.js:21 [2021-10-12T17:23:48.618Z] Error: System.InvalidOperationException: Unable to initialize Blazorise RichTextEdit script
   at Blazorise.RichTextEdit.RichTextEditJsInterop.CheckIsLoaded()
   at Blazorise.RichTextEdit.RichTextEditJsInterop.InitializeJsInterop()
   at Blazorise.RichTextEdit.RichTextEditJsInterop.InitializeEditor(RichTextEdit richTextEdit)
   at Blazorise.RichTextEdit.RichTextEdit.OnFirstAfterRenderAsync()
   at Blazorise.BaseComponent.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

**Comment by stevenlupo** [comment]
Actually, this is happening in the Bootstrap Demo as well: https://bootstrapdemo.blazorise.com/tests/richtextedit

**Comment by stsrki** [comment]
Can you clear the cache? Ctrl+F5 usually helps.

**Comment by stevenlupo** [comment]
I did ctrl+f5, plus I cleared the cache in Chrome, then restarted the browser. It's still broken.

**Comment by stevenlupo** [comment]
Could this be a firewall thing?

**Comment by stevenlupo** [comment]
Yea, it was our firewall. It was blocking these scripts:

https://cdn.quilljs.com/1.3.7/quill.bubble.css
https://cdn.quilljs.com/1.3.7/quill.js
https://cdn.quilljs.com/1.3.7/quill.snow.css

Our network people resolved it. 

Thanks for your help.
