### ISSUE TITLE
Carousel - 'Timer' Causing ObjectDisposedException

### ISSUE THREAD

**Issue by lswatt** [Megabit/Blazorise#3157]
We are using the carousel as a component and getting the following:

`System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Timer'.
   at System.Timers.Timer.set_Enabled(Boolean value)
   at System.Timers.Timer.Start()
   at Blazorise.Carousel.ResetTimer()
   at Blazorise.Carousel.AnimationEnd(CarouselSlide slide)
   at Blazorise.Carousel.<>c__DisplayClass35_0.<<OnTransitionTimerEvent>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<<InvokeAsync>b__9_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Blazorise.Carousel.OnTransitionTimerEvent(Object source, ElapsedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__127_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()`

The current way we're reproducing this error is to just click around each page until it occurs again, we haven't been able to find 100% way to replicate.

**Comment by stsrki** [comment]
Can you tell us what version of Blazorise are you using?

**Comment by Noobeld** [comment]
0.9.5

**Comment by stsrki** [comment]
Tnx. We'll try to investigate.

**Comment by David-Moreira** [comment]
What the heck?
"Basically as soon as you stop a timer, the internal System.Threading.Timer becomes available for Garbage Collection,
sometimes causing the elapsed event not to occur, or sometimes causing a disposed reference exception."

Is this why we have this weird code? haha
![Sem Título](https://user-images.githubusercontent.com/22283161/143508140-982b0505-e778-4bff-86f6-c168fa535834.png)

**Comment by David-Moreira** [comment]
Hoping that the new "Timer" on NET6 will be much better and we can rework this. For now I think I am going to do the same that has been done with the Transition Timer... Otherwise I don't see any other options? Maybe acquire a lock to the `Timer`, that way it won't get gced?

**Comment by stsrki** [comment]
> "Basically as soon as you stop a timer, the internal System.Threading.Timer becomes available for Garbage Collection,
> sometimes causing the elapsed event not to occur, or sometimes causing a disposed reference exception."

what gives?! This feels like a major bug in .NET...

**Comment by stsrki** [comment]
Seems to be true

- https://stackoverflow.com/questions/4962172/why-does-a-system-timers-timer-survive-gc-but-not-system-threading-timer
- https://stackoverflow.com/questions/18136735/can-timers-get-automatically-garbage-collected
