### ISSUE TITLE
.Net 6 & Blazorise 0.9.5 Path Loading Issue

### ISSUE THREAD

**Issue by vmannbfmc** [Megabit/Blazorise#3160]
Hello, 

We have commercial license and are getting this issue. Our base url is "/LetterUpdateTracker" and it results in blazorise having issues with the new .net 6. We have app.UsePathBase("/LetterUpdateTracker"); app.UseStaticFiles(); and base is set to <base href="/LetterUpdateTracker/" />

![image](https://user-images.githubusercontent.com/94996604/143311007-24308368-3334-4486-8c25-106daa47f813.png)

**Comment by stsrki** [comment]
Hi @vmannbfmc 

The files that are giving you 404 are obsolete, starting from v0.9.5. As per [migration notes](https://blazorise.com/news/release-notes/095) under point 7.

You are free to remove them from your `index.html` or `_Host.cshtml` file.

**Comment by vmannbfmc** [comment]
There are no js files in the _Layout.cshtml (.net 6). Those are being dynamically loaded it seems from Blazorise.

**Comment by stsrki** [comment]
Not `_Layout.cshtml`. They were usually in the `_Host.cshtml` .

eg. https://github.com/Megabit/Blazorise/blob/master/Demos/Blazorise.Demo.Bootstrap.Server/Pages/_Host.cshtml

**Comment by vmannbfmc** [comment]
When you start a new .Net 6 project with Visual Studio Professional 2022 it does not add the head and base html to _Host it adds to _Layout. Regardless the point is that there are no includes and no references to Blazorise js files yet Blazorise is trying to load those files, I'm assuming dynamically, and it is not found.

**Comment by vmannbfmc** [comment]
It also has this error:

`Error: Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: https://localhost:7121/LetterUpdateTracker/_content/Blazorise/button.js?v=0.9.5.0
TypeError: Failed to fetch dynamically imported module: https://localhost:7121/LetterUpdateTracker/_content/Blazorise/button.js?v=0.9.5.0
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Blazorise.Modules.JSButtonModule.Initialize(ElementReference elementRef, String elementId, Object options)
   at Blazorise.Button.<OnInitialized>b__12_0()
   at Blazorise.BaseAfterRenderComponent.OnAfterRenderAsync(Boolean firstRender)
   at Blazorise.BaseComponent.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)`

**Comment by vmannbfmc** [comment]
`Error: Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: https://apps-test/LetterUpdateTracker/_content/Blazorise.Bootstrap/modal.js?v=0.9.5.0
TypeError: Failed to fetch dynamically imported module: https://apps-test/LetterUpdateTracker/_content/Blazorise.Bootstrap/modal.js?v=0.9.5.0
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Blazorise.Modules.JSModalModule.OpenModal(ElementReference elementRef, Boolean scrollToTop)
   at Blazorise.Modal.<HandleVisibilityStyles>b__16_0()
   at Blazorise.BaseAfterRenderComponent.OnAfterRenderAsync(Boolean firstRender)
   at Blazorise.BaseComponent.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)`

I think there is an issue with the dynamic loading when you change the path to a new subdirectory using a new base path.

**Comment by stsrki** [comment]
The path error should be fixed. We release a preview yesterday to be tested by our clients before an official 0.9.5.1 release. You can get it by following https://github.com/Megabit/Blazorise#try-preview.

Please let us know if it helps.

**Comment by vmannbfmc** [comment]
It seems to work for local environment but when I move to production or anything other than environment = development then it results in the same error. I'm using 0.9.5.1.

**Comment by stsrki** [comment]
Is there any chance you could create a small project to reproduce it on our side?

**Comment by David-Moreira** [comment]
Also is there anything that can be blocking the static assets on your production server?
if you visit https://apps-test/LetterUpdateTracker/_content/Blazorise.Bootstrap/modal.js?v=0.9.5.0 directly, does the server handle you the javascript file?

**Comment by stsrki** [comment]
Hey @vmannbfmc, did you try to test the solution that @David-Moreira has given? Any info would be helpful.

**Comment by David-Moreira** [comment]
@vmannbfmc any news?

**Comment by vmannbfmc** [comment]
Sorry for the delay. It seems the update did work as long as the layout's base is set to "/LetterUpdateTracker" and the startup has app.UsePathBase("/LetterUpdateTracker") and app.UseStaticFiles() is set (without parameters).

**Comment by vmannbfmc** [comment]
It seems I am having this issue again with Blazorise with another project on .Net 6. I am on 0.9.5.6.

[2022-02-28T20:26:36.501Z] Error: Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: https://localhost:7082/CheckRequest/_content/Blazorise/button.js?v=0.9.5.6

**Comment by stsrki** [comment]
Did you change the base path? `app.UsePathBase("/CheckRequest")`

**Comment by vmannbfmc** [comment]
Yes, and I am using app.UseStaticFiles();

**Comment by stsrki** [comment]
Do you also have it defined in `index.html` or `_Host.cshtml`?

**Comment by vmannbfmc** [comment]
Yes, I do, on the <base> tag.

**Comment by David-Moreira** [comment]
If your base path is CheckRequest, then you need to allocate the static files at CheckRequest base path.

By setting `app.UseStaticFiles("/CheckRequest");`

**Comment by vmannbfmc** [comment]
I have already tried that and it still does not work, error is the same:

Error: Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: https://localhost:7082/CheckRequest/_content/Blazorise/button.js?v=0.9.5.6
TypeError: Failed to fetch dynamically imported module: https://localhost:7082/CheckRequest/_content/Blazorise/button.js?v=0.9.5.6
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Blazorise.Modules.JSButtonModule.Initialize(ElementReference elementRef, String elementId, Object options)
   at Blazorise.Button.<OnInitialized>b__12_0()
   at Blazorise.BaseAfterRenderComponent.OnAfterRenderAsync(Boolean firstRender)
   at Blazorise.BaseComponent.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by David-Moreira** [comment]
Can I ask that you create a repo? Thanks

**Comment by vmannbfmc** [comment]
I created a repo and started doing some further testing and *finally* solved the problem. If you have your ASPNETCORE_ENVIRONMENT variable set to anything other than development you need to update your .NET 6 Program.cs file to the following:

var builder = WebApplication.CreateBuilder(new WebApplicationOptions
{
    WebRootPath = "wwwroot",
    Args = args
});
builder.WebHost.UseStaticWebAssets();

**Comment by stsrki** [comment]
@vmannbfmc thanks for posting the solution!
