### ISSUE TITLE
validation error message crashes the program 

### ISSUE THREAD

**Issue by janseris** [Megabit/Blazorise#3331]
**Describe the bug**
        [RegularExpression("[a-z]", ErrorMessage = "!\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~")]

Note: the symbols might not be properly displayed. It is just a list of ASCII symbols 33 to 126 inclusive. I call it "visible ASCII characters" as it is "printable ASCII characters" except space which is ASCII 32.

![blazorise bug 2](https://user-images.githubusercontent.com/64279914/149686512-efd9787d-7a8b-4eac-9465-b5efea474ea6.png)

this annotation on a model field crashes the program with the following stack trace when the validation error message should be displayed

`warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Input string was not in a correct format.
      System.FormatException: Input string was not in a correct format.
         at System.Text.ValueStringBuilder.ThrowFormatError()
         at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
         at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
         at System.String.Format(IFormatProvider provider, String format, Object arg0, Object arg1)
         at System.ComponentModel.DataAnnotations.RegularExpressionAttribute.FormatErrorMessage(String name)
         at System.ComponentModel.DataAnnotations.ValidationAttribute.IsValid(Object value, ValidationContext validationContext)
         at System.ComponentModel.DataAnnotations.ValidationAttribute.GetValidationResult(Object value, ValidationContext validationContext)
         at System.ComponentModel.DataAnnotations.Validator.TryValidate(Object value, ValidationContext validationContext, ValidationAttribute attribute, ValidationError& validationError)
         at System.ComponentModel.DataAnnotations.Validator.GetValidationErrors(Object value, ValidationContext validationContext, IEnumerable`1 attributes, Boolean breakOnFirstError)
         at System.ComponentModel.DataAnnotations.Validator.TryValidateProperty(Object value, ValidationContext validationContext, ICollection`1 validationResults)
         at Blazorise.EditContextValidator.ValidateField(EditContext editContext, ValidationMessageStore messages, FieldIdentifier& fieldIdentifier, Func`3 messageLocalizer)
         at Blazorise.DataAnnotationValidationHandler.Validate(IValidation validation, Object newValidationValue)
         at Blazorise.DataAnnotationValidationHandler.ValidateAsync(IValidation validation, Object newValidationValue, CancellationToken cancellationToken)
         at Blazorise.Validation.ValidateAsync(Object newValidationValue)
         at Blazorise.Validations.TryValidateAll()
         at Blazorise.Validations.ValidateAll()
         at BlazorApp1.Pages.User.Registration.Register() in C:\Users\janse\Desktop\práce\Ordinace\BlazorApp1\Pages\User\Registration.razor:line 233
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Blazorise.Button.ClickHandler()
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'lZ14y1LS1pHM4DyWYZSeW4j6h4PgVNPAdgidiZy1niI'.
      System.FormatException: Input string was not in a correct format.
         at System.Text.ValueStringBuilder.ThrowFormatError()
         at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
         at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
         at System.String.Format(IFormatProvider provider, String format, Object arg0, Object arg1)
         at System.ComponentModel.DataAnnotations.RegularExpressionAttribute.FormatErrorMessage(String name)
         at System.ComponentModel.DataAnnotations.ValidationAttribute.IsValid(Object value, ValidationContext validationContext)
         at System.ComponentModel.DataAnnotations.ValidationAttribute.GetValidationResult(Object value, ValidationContext validationContext)
         at System.ComponentModel.DataAnnotations.Validator.TryValidate(Object value, ValidationContext validationContext, ValidationAttribute attribute, ValidationError& validationError)
         at System.ComponentModel.DataAnnotations.Validator.GetValidationErrors(Object value, ValidationContext validationContext, IEnumerable`1 attributes, Boolean breakOnFirstError)
         at System.ComponentModel.DataAnnotations.Validator.TryValidateProperty(Object value, ValidationContext validationContext, ICollection`1 validationResults)
         at Blazorise.EditContextValidator.ValidateField(EditContext editContext, ValidationMessageStore messages, FieldIdentifier& fieldIdentifier, Func`3 messageLocalizer)
         at Blazorise.DataAnnotationValidationHandler.Validate(IValidation validation, Object newValidationValue)
         at Blazorise.DataAnnotationValidationHandler.ValidateAsync(IValidation validation, Object newValidationValue, CancellationToken cancellationToken)
         at Blazorise.Validation.ValidateAsync(Object newValidationValue)
         at Blazorise.Validations.TryValidateAll()
         at Blazorise.Validations.ValidateAll()
         at BlazorApp1.Pages.User.Registration.Register() in C:\Users\janse\Desktop\práce\Ordinace\BlazorApp1\Pages\User\Registration.razor:line 233
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Blazorise.Button.ClickHandler()
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)`

**Expected behavior**
a list of ASCII 33 to 126 are shown to the user instead of crash

Does this mean that the error message could maybe execute JS code on client because it crashed somewhere in JS interop?

**Comment by stsrki** [comment]
I'm not sure how you managed to do it. Can you please some sample code so that we can reproduce the error on our side?

**Comment by janseris** [comment]
[Blazorise Validation message bug.zip](https://github.com/Megabit/Blazorise/files/7883356/Blazorise.Validation.message.bug.zip)
Reproduce bug: enter password of length 1 and click Log In to show error validation message

**Comment by stsrki** [comment]
I have tested and it is failing as expected. Internally we're depending an .NET validators for data-annotations. And it seems that `RegularExpression` is expecting max of **2** arguments for the `ErrorMessage` string format. If you change your code to

`$"Length: {PasswordMinLength} to {PasswordMaxLength} characters. Accepted characters: {ASCIIVisibleChars}"`

or

`"{0} should match {1} characters."`

You will see the result. At least something.

---

My advice is to hardcode the error if you can. Or at least some parts of it.

**Comment by janseris** [comment]
> I have tested and it is failing as expected. Internally we're depending an .NET validators for data-annotations. And it seems that `RegularExpression` is expecting max of **2** arguments for the `ErrorMessage` string format. If you change your code to
> 
> `$"Length: {PasswordMinLength} to {PasswordMaxLength} characters. Accepted characters: {ASCIIVisibleChars}"`
> 
> or
> 
> `"{0} should match {1} characters."`
> 
> You will see the result. At least something.
> 
> My advice is to hardcode the error if you can. Or at least some parts of it.

The error persists when there is 1 argument in the ErrorMessage.
[RegularExpression(PasswordRegex, ErrorMessage = $"Accepted characters: {ASCIIVisibleChars}")]
