### ISSUE TITLE
Chart with aspect ratio throws unhandled exception

### ISSUE THREAD

**Issue by kachna96** [Megabit/Blazorise#3560]
**Describe the bug**
Hi, after upgrading to chartjs v3 (and Blazorise 1.0.0/1), we get from time to time unhandled exception in chart extension.
I wasn't able to reliably reproduce it, but we have quite complex page containing doughnut chart with custom aspect ratio in options object and StateHasChanged() in our code that gets called after some action shortly after initialization and I think it might interfere with the chart rendering, but it's just my guess.
The log points to this line in js file: [https://github.com/Megabit/Blazorise/blob/master/Source/Extensions/Blazorise.Charts/wwwroot/charts.js#L172](https://github.com/Megabit/Blazorise/blob/master/Source/Extensions/Blazorise.Charts/wwwroot/charts.js#L172)

I tried to remove the if clause using local override in dev tools and it seems to be working ok and custom aspect ratio is respected, so maybe it's not needed anymore for v3? I haven't seen the exception since we removed it.
What do you think?

> blazor.webassembly.js?v=6.0.2:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot set property aspectRatio of #<dn> which has only a getter
      TypeError: Cannot set property aspectRatio of #<dn> which has only a getter
          at Module.setOptions (https://xxx.com/_content/Blazorise.Charts/charts.js?v=1.0.1.0:172:31)
          at https://xxx.com/_framework/blazor.webassembly.js?v=6.0.2:1:3332
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (xxx.com/_framework/blazor.webassembly.js?v=6.0.2:1:3306)
          at Object.St [as invokeJSFromDotNet] (xxx.com/_framework/blazor.webassembly.js?v=6.0.2:1:59853)
          at _mono_wasm_invoke_js_blazor (xxx.com/_framework/dotnet.6.0.3.h5gi5nwtz2.js:1:194973)
          at https://xxx.com/_framework/dotnet.wasm:wasm-function[219]:0x1a0fa
          at https://xxx.com/_framework/dotnet.wasm:wasm-function[167]:0xcac8
          at https://xxx.com/_framework/dotnet.wasm:wasm-function[166]:0xb9db
          at https://xxx.com/_framework/dotnet.wasm:wasm-function[2810]:0xabae2
Microsoft.JSInterop.JSException: Cannot set property aspectRatio of #<dn> which has only a getter
TypeError: Cannot set property aspectRatio of #<dn> which has only a getter
    at Module.setOptions (https://xxx.com/_content/Blazorise.Charts/charts.js?v=1.0.1.0:172:31)
    at https://xxx.com/_framework/blazor.webassembly.js?v=6.0.2:1:3332
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://xxx.com/_framework/blazor.webassembly.js?v=6.0.2:1:3306)
    at Object.St [as invokeJSFromDotNet] (https://xxx.com/_framework/blazor.webassembly.js?v=6.0.2:1:59853)
    at _mono_wasm_invoke_js_blazor (https://xxx.com/_framework/dotnet.6.0.3.h5gi5nwtz2.js:1:194973)
    at https://xxx.com/_framework/dotnet.wasm:wasm-function[219]:0x1a0fa
    at https://xxx.com/_framework/dotnet.wasm:wasm-function[167]:0xcac8
    at https://xxx.com/_framework/dotnet.wasm:wasm-function[166]:0xb9db
    at https://xxx.com/_framework/dotnet.wasm:wasm-function[2810]:0xabae2
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference , String , Object[] )
   at Blazorise.Charts.JSChartModule.<SetOptions>d__4`1[[Blazorise.Charts.DoughnutChartOptions, Blazorise.Charts, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Blazorise.Charts.BaseChart`4.<SetOptionsObject>d__16[[Blazorise.Charts.DoughnutChartDataset`1[[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Blazorise.Charts, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null],[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Blazorise.Charts.DoughnutChartOptions, Blazorise.Charts, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null],[Blazorise.Charts.DoughnutChartModel, Blazorise.Charts, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Ori.Olaf.TestResults.Web.ClientServices.Components.Charts.TestReleases.PassRatioTestRunDoughnutChart.RedrawAsync()
   at Ori.Olaf.TestResults.Web.Client.Shared.Charts.OriTestRunDoughnutChart.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )
window.Module.s.printErr @ blazor.webassembly.js?v=6.0.2:1

**Comment by kachna96** [comment]
yes, I have 3.7.1, but it should be ok I think
`<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/chart.min.js"></script>`
