### ISSUE TITLE
Datagrid Dispose Error

### ISSUE THREAD

**Issue by aizusama** [Megabit/Blazorise#3783]
When I navigate from a page that renders datagrid to another page that renders another datagrid. It gives me this error.
        
[2022-05-11T08:30:23.791Z] Error: System.AggregateException: Exceptions were encountered while disposing components. (One or more errors occurred. (Object reference not set to an instance of an object.)) (One or more errors occurred. (Object reference not set to an instance of an object.)) (One or more errors occurred. (Object reference not set to an instance of an object.))
 ---> System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Blazorise.DataGrid.DataGridColumn`1.DisposeSubscriptions()
   at Blazorise.DataGrid.DataGridColumn`1.DisposeAsync(Boolean disposing)
   at Blazorise.BaseAfterRenderComponent.DisposeAsync()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
 ---> (Inner Exception #1) System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Blazorise.DataGrid.DataGridColumn`1.DisposeSubscriptions()
   at Blazorise.DataGrid.DataGridColumn`1.DisposeAsync(Boolean disposing)
   at Blazorise.BaseAfterRenderComponent.DisposeAsync()
   --- End of inner exception stack trace ---<---

 ---> (Inner Exception #2) System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Blazorise.DataGrid.DataGridColumn`1.DisposeSubscriptions()
   at Blazorise.DataGrid.DataGridColumn`1.DisposeAsync(Boolean disposing)
   at Blazorise.BaseAfterRenderComponent.DisposeAsync()
   --- End of inner exception stack trace ---<---

**Comment by aizusama** [comment]
Im not sure what fixed it. After restarting my Visual Studio. The problem is now gone. Closing this.
