### ISSUE TITLE
Cannot display scatter chart (worked in previous version)

### ISSUE THREAD

**Issue by TheZlodziej** [Megabit/Blazorise#3866]
**Describe the bug**
I'm not sure if I'm doing something wrong but in the previous version (when no scatter chart was available, I think it was 0.9.5) this code (for line chart with invisible lines) worked. Once I tried to change this for 'newer' version (1.0.4) that uses scatter chart class, I keep getting the error in my dev tools
```js
Error: Microsoft.JSInterop.JSException: Cannot read properties of undefined (reading 'pie')
TypeError: Cannot read properties of undefined (reading 'pie')
    at https://localhost:7018/_content/Blazorise.Charts/charts.js?v=1.0.4.0:18:22
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Blazorise.Charts.JSChartModule.Initialize[TItem,TOptions](DotNetObjectReference`1 dotNetObjectReference, Object eventOptions, ElementReference canvasRef, String canvasId, ChartType type, ChartData`1 data, TOptions options, String dataJsonString, String optionsJsonString, Object optionsObject)
   at Blazorise.Charts.BaseChart`4.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**To Reproduce**
This is my code for making faster scatter chart with multiple X-Y entries:
```c#
@typeparam TypeOfItem

<Chart @ref="_chart" Type="ChartType.Scatter" TItem="TypeOfItem" OptionsObject="@_options"/>

@code{
    [Parameter] [EditorRequired] public List<List<TypeOfItem>> DataSets { get; set; } = new();
    [Parameter] public List<string> Labels { get; set; } = new();
    [Parameter] public RenderFragment? ChildContent { get; set; }

    private Chart<TypeOfItem>? _chart;
    private string[] _labels = { "Red", "Green", "Blue", "Yellow", "Purple", "Orange" };
    private List<string> _backgroundColors = new List<string>
    {
        ChartColor.FromRgba(255, 99, 132, 0.2f),
        ChartColor.FromRgba( 75, 192, 192, 0.2f),
        ChartColor.FromRgba(54, 162, 235, 0.2f),
        ChartColor.FromRgba(255, 206, 86, 0.2f),
        ChartColor.FromRgba(75, 192, 192, 0.2f),
        ChartColor.FromRgba(153, 102, 255, 0.2f),
        ChartColor.FromRgba(255, 159, 64, 0.2f) 
    };

    private List<string> _borderColors = new List<string>
    {
        ChartColor.FromRgba(255, 99, 132, 1f),
        ChartColor.FromRgba( 75, 192, 192, 1f),
        ChartColor.FromRgba(54, 162, 235, 1f),
        ChartColor.FromRgba(255, 206, 86, 1f),
        ChartColor.FromRgba(75, 192, 192, 1f),
        ChartColor.FromRgba(153, 102, 255, 1f),
        ChartColor.FromRgba(255, 159, 64, 1f) 
    };

    ScatterChartOptions _options = new()
    {
        AspectRatio = 1.5
    };

    protected override void OnParametersSet()
    {
        if (_chart is null)
            return;

        InvokeAsync(async () =>
        {
            for (int i = 0; i < DataSets.Count; i++)
            {
                await _chart.SetData(i, DataSets[i]);
            }

            await _chart.Update();
        });
    }

    protected override async Task OnAfterRenderAsync( bool firstRender )
    {
        if (_chart is null)
            return;

        if (!firstRender)
            return;

        for (int i = 0; i < DataSets.Count; i++)
        {
            await _chart.Clear();
            await _chart.AddDataSet(GetChartDataset(i));
        }
    }

    private async Task HandleRedraw<TDataSet, TItem, TOptions, TModel>(BaseChart<TDataSet, TItem, TOptions, TModel> chart, params Func<TDataSet>[] getDataSet)
        where TDataSet : ChartDataset<TItem>
        where TOptions : ChartOptions
        where TModel : ChartModel
        where TItem : TypeOfItem
    {
        await chart.Clear();
        await chart.AddLabelsDatasetsAndUpdate(_labels, getDataSet.Select(x=>x.Invoke()).ToArray());
    }

    async Task SetDataAndUpdate<TDataSet, TItem, TOptions, TModel>(BaseChart<TDataSet, TItem, TOptions, TModel> chart, Func<List<TItem>> items )
        where TDataSet : ChartDataset<TItem>
        where TOptions : ChartOptions
        where TModel : ChartModel
        where TItem : TypeOfItem
    {
        if (_chart is null)
            return;

        for (int i = 0; i < DataSets.Count; i++)
        {
            await _chart.SetData(i, DataSets[i]);
        }

        await chart.Update();
    }

    private ScatterChartDataset<TypeOfItem> GetChartDataset(int i)
    {
        return new ScatterChartDataset<TypeOfItem>
        {
            Label = Labels[i],
            Data = DataSets[i],
            BackgroundColor = _backgroundColors[i],
            BorderColor = _borderColors[i],
            PointRadius = 3,
            BorderWidth = 1,
            PointBorderColor = _borderColors[i]
        };
    }
}
```

Usage of this code would be:
```c#
<QuickScatterChart TypeOfItem="ScatterChartPoint" DataSets="@_dataSets" Labels="@_dataSetsLabels"/>
```
where _dataSets is ```List<List<ScatterChartPoint>>``` and _dataSetsLabels is ```List<string>```

**Expected behavior**
In previous versions this worked as intended, the DataSets property held list of lists of points (X-Y pairs) that were displayed in different colors and given proper label

**Screenshots**
![image](https://user-images.githubusercontent.com/33941527/171700754-6a6e56bc-55c4-4c36-918b-b64b9c368bf8.png)

**Comment by paiden** [comment]
Had the same issue after upgrading my Blazorise version to 1.0.6

Seems the JS charting library was incompatible

I had to change the script include in `_Host.cshtml` from   
```javascript
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
``` 
to 

```javascript
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/chart.min.js"></script>
```
as this is the URL from the latest documentation.

Now my charts work again.

HTH

**Comment by stsrki** [comment]
Sorry for not getting to this issue sooner.

As @paiden has already mentioned, we are now using chart v3.x, so you should upgrade your packages. You can look at the migration notes for reference https://blazorise.com/news/release-notes/100

**Comment by TheZlodziej** [comment]
Hey, thanks for your reply. Yes, I can confirm, changing the version fixed the issue. Haven't thought of that :P Thanks for help!
