### ISSUE TITLE
Javascript error when using FileEdit with Ant Design

### ISSUE THREAD

**Issue by GeertvanHorrik** [Megabit/Blazorise#3964]
**Describe the bug**

Trying to add a FileEdit to a page:

```
<FileEdit Changed="async (e) => await UploadFileAsync(e)"
            Ended="async (e) => await OnFileEditEndedAsync(e)"
            Placeholder="Select zip file"
            Filter=".zip" />
```

**To Reproduce**

1. Create ant design blazorise
2. Add FileEdit
3. Try using the component

```
Microsoft.JSInterop.JSException: Could not find 'open' ('open' was undefined).
Error: Could not find 'open' ('open' was undefined).
    at https://localhost:5001/_framework/blazor.webassembly.js:1:328
    at Array.forEach (<anonymous>)
    at a.findFunction (https://localhost:5001/_framework/blazor.webassembly.js:1:296)
    at _ (https://localhost:5001/_framework/blazor.webassembly.js:1:2437)
    at https://localhost:5001/_framework/blazor.webassembly.js:1:3325
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.webassembly.js:1:3306)
    at Object.St [as invokeJSFromDotNet] (https://localhost:5001/_framework/blazor.webassembly.js:1:59938)
    at _mono_wasm_invoke_js_blazor (https://localhost:5001/_framework/dotnet.6.0.7.ox20i1h7bg.js:1:195300)
    at wasm://wasm/00971e46:wasm-function[219]:0x1a490
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at Blazorise.Modules.JSFileEditModule.OpenFileDialog(ElementReference elementRef, String elementId)
   at Blazorise.AntDesign.FileEdit.OnButtonClickHandled()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

I checked the sources and this file is included:

```
/_content/Blazorise/fileEdit.js?v=1.0.5.0
```

**Comment by David-Moreira** [comment]
@stsrki can you help here? It seems we had a custom ant design implementation that might've gotten lost in some version.

**AntDesign.FileEdit.razor**
![image](https://user-images.githubusercontent.com/22283161/179625711-98266476-5c86-46e5-875b-aed7f5844310.png)
which triggers an open action, which we currently do not have since our current implementation uses fileEdit.js.initialize to listen to the `input type="file"` onchange handler.

My guess is that it should just trigger the `input type="file"` behind the covers, but it would be ideal to have the original implementation instead of doing a new one. @stsrki think you can easily get it in the sea of commits, or should we just go ahead and provide a new one?

**Comment by stsrki** [comment]
I can try looking into it, but can't promise it will be fast considering all the other work at the moment.

**Comment by David-Moreira** [comment]
Haha it was just if you'd quickly know what I am talking about/get it. Otherwise I guess it might be faster to just provide a new working implementation then. My guess is that it won't take too long. I'll take care of it. Thanks. :)
