### ISSUE TITLE
Bar - Vertical Bar Toggler - External (controlled by Top Bar) - Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by drma-dev** [Megabit/Blazorise#4105]
I tried to apply this example and I couldn't. (I'm using the preview version, I don't know if this happens in the stable version)

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Blazorise.BarToggler.BuildClasses(ClassBuilder builder)
   at Blazorise.Utilities.ClassBuilder.get_Class()
   at Blazorise.BaseComponent.get_ClassNames()
   at Blazorise.Bootstrap.BarToggler.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

**Comment by David-Moreira** [comment]
It's been a while, can we ask that you try this again? :)

**Comment by drma-dev** [comment]
now i managed to make it work.

a question: instead of hiding the menu, is there any way to make it thin just showing the icons?

**Comment by David-Moreira** [comment]
@stsrki?

**Comment by stsrki** [comment]
Yes, there is. You need to set the Bar `Mode="BarMode.VerticalSmall"`.

PS. closing now as the original issue is solved.

**Comment by drma-dev** [comment]
@stsrki 
both modes go to hidden mode. isn't there a way to go from large mode to icon mode only when you click the toogle button?
