### ISSUE TITLE
Blazorise doesn't work with Maui blazor on iphone but it works on ios simulators

### ISSUE THREAD

**Issue by emanuelpaul** [Megabit/Blazorise#4160]
**Describe the bug**
Blazorise doesn't work on dotnet maui blazor on iPhones but it works on iOS simulators.
Tested on 
- MacOS 12.6.
- XCode 13.3.1 (13E500a)
- Dotnet sdk: 6.0.401
- dotnet workloads:
Installed Workload Ids      Manifest Version      Installation Source
---------------------------------------------------------------------
wasm-tools                  6.0.9/6.0.400         SDK 6.0.400
macos                       12.3.454/6.0.400      SDK 6.0.400
maui-maccatalyst            6.0.540/6.0.400       SDK 6.0.400
maui-ios                    6.0.540/6.0.400       SDK 6.0.400
maui-android                6.0.540/6.0.400       SDK 6.0.400

It works fine on simulators:
- iphone se 3 - iOS 16
- iphone se 3 - iOS 15.4

It doesn't work on real iphone devices. I tested on:
- iphone se 3 - iOS 16
- iphone 6s - iOS 15.6.1

Exception that occurs:
```
Instance property 'Disposables' is not defined for type 'Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope' (Parameter 'propertyName')
   at System.Linq.Expressions.Expression.Property(Expression , String )
   at
```
Might be related to #4137 
It seems to be generated by line:
```
if ( disposablesGetter is null )
            disposablesGetter = ExpressionCompiler.CreatePropertyGetter<IList<object>>( ServiceProvider, PROPERTY_DISPOSABLES );
```

**To Reproduce**
- clone repo: https://github.com/emanuelpaul/BlazoriseMaui
- replace the value of CodesignKey and CodesignProvision with your values
- run command `dotnet build -t:Run -f net6.0-ios -p:_DeviceName={replace_with_your_iphone_identifier} -r ios-arm64`

**Expected behavior**
The app should run on the iPhone.
Github repo: https://github.com/emanuelpaul/BlazoriseMaui

**Screenshots**
![image](https://user-images.githubusercontent.com/2426861/193230383-77a731ee-3a77-444c-b3a3-f81dd3fad444.png)

**Additional context**
Exception details:
Instance property 'Disposables' is not defined for type 'Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope' (Parameter 'propertyName')
   at System.Linq.Expressions.Expression.Property(Expression , String )
   at Blazorise.ExpressionCompiler.CreatePropertyGetter[IList`1](Object instance, String propertyName)
   at Blazorise.ComponentDisposer.LoadServiceProviderDisposableList()
   at Blazorise.ComponentDisposer..ctor(IServiceProvider serviceProvider)
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object , Object[] , Boolean )
   at System.Reflection.RuntimeConstructorInfo.DoInvoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags , Binder , Object[] , CultureInfo )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite , RuntimeResolverContext , ServiceProviderEngineScope , RuntimeResolverLock )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite , RuntimeResolverContext )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeServiceProviderEngine.<>c__DisplayClass4_0.<RealizeService>b__0(ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type )
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass7_0.<CreateInitializer>g__Initialize|1(IServiceProvider , IComponent )
   at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider , IComponent )
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider , Type )
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateComponent(Type )
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& , Int32 )
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& , Int32 )
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& , Int32 )
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& , Int32 )
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& , Int32 , Int32 , Int32 , Int32 )
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer , RenderBatchBuilder , Int32 , ArrayRange`1 , ArrayRange`1 )
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder , RenderFragment , Exception& )
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry )
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

**Comment by stsrki** [comment]
Yes, the #4137 is the same problem. Expect the 1.1.1 update today with the fix applied.

**Comment by emanuelpaul** [comment]
> Yes, the #4137 is the same problem. Expect the 1.1.1 update today with the fix applied.

cool, thanks !

**Comment by emanuelpaul** [comment]
I updated to version 1.1.1 but the error seems to persist.

**Comment by David-Moreira** [comment]
> I updated to version 1.1.1 but the error seems to persist.

Can you try this workaround while we take a look at it?

----

> As suggested by @stsrki I added this class to override `IComponentDisposer`, then registered for DI. In case this is useful for anyone else.
> 
> ```
> using Blazorise;
> 
> namespace Mis.Mw.App.Client
> {
>     public class BlazoriseWorkaround : IComponentDisposer
>     {
>         void IComponentDisposer.Dispose<TComponent>(TComponent component)
>         {
>             // nothing to see here
>         }
>     }
> }
> ```
> 
> Program.cs
> 
> ```
>             builder.Services
>               .AddBlazorise(options =>
>               {
>                   options.Immediate = true;
>               })
>               .AddBlazoriseRichTextEdit()
>               .AddBootstrapComponents()
>               .AddBootstrapProviders()
>               .AddFontAwesomeIcons();
> 
>             builder.Services.AddScoped<IComponentDisposer, BlazoriseWorkaround>();
> ```

**Comment by emanuelpaul** [comment]
It seems to work using this workaround. I'll use this for now.

**Comment by David-Moreira** [comment]
I still haven't tested this, and I was wondering where the hell am I going to get an IPhone to test this, haha, My guess is the the behaviour will be the same in Android, right?

Is there some free resource you can use to emulate as a real phone, that you can recomend @emanuelpaul ? 
My guess is that the test will still be equivalent.

But from re-reading your issue... The problem seems to be quite the same we're already facing with Blazor WebAssembly. 
It works with regular builds ("simulators" in your case), but once published it also throws a very similar error.

Again, this is a new feature, and everything should be working as before with no consequences by using the workaround of overriding the `IComponentDisposer` with an empty implementation.

**Comment by emanuelpaul** [comment]
The issue seems to occur only on the iPhone, it works fine on the simulator(a simulator is the equivalent of the android emulator for ios apps). I haven't tested on android but on android it might work because android has fewer restrictions than the ios. I'll try to test on android next week. 
One of the main restrictions when creating the apps for ios is that the app that is developed needs to be built on a mac. So in practice to develop ios apps and to test them the following are needed: 
- a mac
- an iphone
- apple developer account(optional but highly recommended).

I'll use this workaround for now.

**Comment by stsrki** [comment]
> * a mac
> * an iphone
> * apple developer account(optional but highly recommended).

All of which we don't have at the moment :(

**Comment by emanuelpaul** [comment]
> > * a mac
> > * an iphone
> > * apple developer account(optional but highly recommended).
> 
> All of which we don't have at the moment :(

Ok, np I'll use the workaround. I can try to look on this after .NET 7 is out because it should have better tooling for Maui.

**Comment by David-Moreira** [comment]
@stsrki Have we released the patch with the #4182 PR? Can we ask @emanuelpaul to test this?

**Comment by stsrki** [comment]
Not yet. It's on schedule for 1.1.2.

**Comment by emanuelpaul** [comment]
I can test it after it's out.

**Comment by David-Moreira** [comment]
@emanuelpaul can you test it, please? Really appreciated. :)

**Comment by emanuelpaul** [comment]
For me now in release mode it just crashes directly without any error.
In debug works fine.
