### ISSUE TITLE
Error when updating from 1.06 to 1.1.4: Unable to set property 'Clicked' on object of type 'Blazorise.Bootstrap5.Button'.

### ISSUE THREAD

**Issue by sturlath** [Megabit/Blazorise#4332]
This may very well be something just related to abp.io but I updated a brand-new version of their 6.0.1 Blazor WASM to use the new 1.1.4.1 and when I run it, I get the following exception.

I don´t see any abp stuff in the error so sending it your way
       
```xml
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Unable to set property 'Clicked' on object of type 'Blazorise.Bootstrap5.Button'. The error was: Specified cast is not valid.
System.InvalidOperationException: Unable to set property 'Clicked' on object of type 'Blazorise.Bootstrap5.Button'. The error was: Specified cast is not valid.
 ---> System.InvalidCastException: Specified cast is not valid.
   at Microsoft.AspNetCore.Components.Reflection.PropertySetter.CallPropertySetter[Button,EventCallback`1](Action`2 setter, Object target, Object value)
   at Microsoft.AspNetCore.Components.Reflection.PropertySetter.SetValue(Object target, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|3_0(Object target, PropertySetter writer, String parameterName, Object value)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|3_0(Object target, PropertySetter writer, String parameterName, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
   at Microsoft.AspNetCore.Components.ParameterView.SetParameterProperties(Object target)
   at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
   at Blazorise.BaseComponent.SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
```

**Comment by sturlath** [comment]
[Here](https://github.com/sturlath/Acme.BookStore) you go @David-Moreira. The project is updated to 1.1.4.1. Downgrade to 1.0.6 and see it work. 

To run this, you need to set multiple start-up projects. 
![image](https://user-images.githubusercontent.com/2386572/204092764-39f47e50-962d-4a48-90f9-bdbc9a15ee65.png)

**Comment by stsrki** [comment]
PS. You first need to run `Acme.BookStore.DbMigrator`.

**Comment by stsrki** [comment]
I can also reproduce an error but other than that I don't see any call-stack that could help me find the cause. @sturlath Did you try to report this on ABP? I have noticed that they didn't update all packages to the same latest version

![image](https://user-images.githubusercontent.com/900302/204096709-b0cb5b15-506f-4bf3-b742-b1f2d2f91f93.png)

**Comment by sturlath** [comment]
> PS. You first need to run Acme.BookStore.DbMigrator.
Sorry forgot about that one

> Did you try to report this on ABP?
No but will now. I´ll mention this there
