### ISSUE TITLE
CSS/JS Path is relative instead of root

### ISSUE THREAD

**Issue by vishalsmart** [Megabit/Blazorise#4674]
**Describe the bug**
When any components are being used in pages or sub-pages,  components are trying to render in relative path. It should be on root path.

Example: 
https://localhost:5092/dashcams_content/Blazorise/closable.js?v=1.2.1.0
Expected:
https://localhost:5092/_content/Blazorise/closable.js?v=1.2.1.0

**To Reproduce**
1. Create Project
2. Use Components in pages instead of index or / path
3. Try to navigate between pages
4. When component re-renders, it is going to ask for relative path.

**Error**
TypeError: Failed to fetch dynamically imported module: https://localhost:5092/dashcams_content/Blazorise/closable.js?v=1.2.1.0
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.IJSObjectReference, Microsoft.JSInterop, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Blazorise.Modules.BaseJSModule.InvokeSafeVoidAsync(String identifier, Object[] args)
   at Blazorise.Components.Autocomplete`2.<<OnInitializedAsync>b__18_0>d[[ELDMandate.Blazor.Shared.Models.lastLocation, ELDMandate.Blazor.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at Blazorise.BaseAfterRenderComponent.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by David-Moreira** [comment]
The static files should be served along the application's path,
You should be able to get it to work by adding `app.UseStaticFiles("/dashcams");` to your startup.

Let us know if this helps.

**Comment by vishalsmart** [comment]
Hi David, 

This is not working as I am using WASM and also I will be having many paths so configuring will not work for me.

As a temporary solution what I did is I forked your repo and changed all modules like below:
public override string ModuleFileName => $"/_content/Blazorise.Bootstrap5/modal.js?v={VersionProvider.Version}";

I changed path "./" to "/" which solved my problem. 

Hope you will update in next release.

**Comment by David-Moreira** [comment]
Hello @vishalsmart what do you mean multiple paths? multiple applications?
The configuration should be one time per application, you just define where you want to allocate your static files, and they should be readily available in that path just as your application is served from that same base path.

Can you send us a repro with this problem for us to analyze?
Thanks!

**Comment by David-Moreira** [comment]
Ah that's great! Thanks for letting us know!
