### ISSUE TITLE
Autocomplete multiple checkbox selection, when first page loads if user instead of searching, press BackSpace button of keyboard if will throw an exception as  follows :

### ISSUE THREAD

**Issue by David-Moreira** [Megabit/Blazorise#4728]
This is not still fixed in autoComplete multiple checkbox selection, when first page loads if user instead of searching, press BackSpace button of keyboard if will throw an exception as  follows :

[2023-04-10T05:10:11.992Z] Error: System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetLast[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.LastOrDefault[TSource](IEnumerable`1 source)
   at Blazorise.Components.Autocomplete`2.OnTextKeyDownHandler(KeyboardEventArgs eventArgs)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

blazorise version 1.2.2

_Originally posted by @4taghavi in https://github.com/Megabit/Blazorise/issues/4622#issuecomment-1501402027_

**Comment by David-Moreira** [comment]
@4taghavi Can you provide a repro? I'm unable to reproduce.
