### ISSUE TITLE
DataGridColumn Editable toggle result in KeyNotFoundException

### ISSUE THREAD

**Issue by SorioliComputec** [Megabit/Blazorise#4903]
**Describe the bug**
I have a simple datagrid with TItem as this class:

```
public class GridItem
{
    public int Id { get; set; }
    public string Name { get; set; }    
}
```

The datagrid:

```
<DataGrid TItem="GridItem" Data="items" Editable ShowPager>
    <DataGridColumns>
        <DataGridColumn Field="@nameof(GridItem.Id)" Caption="Id"></DataGridColumn>
        <DataGridColumn Field="@nameof(GridItem.Name)" Caption="Name" Editable="isEditable"></DataGridColumn>
    </DataGridColumns>
    <ButtonRowTemplate>
        <Button Color="Color.Primary" Clicked="@(() => EditGridItemClick(context))">
            <Icon Name="IconName.Edit" />
        </Button>
        <Button Color="Color.Danger" Clicked="@context.DeleteCommand.Clicked">
            <Icon Name="IconName.Delete" />
        </Button>
    </ButtonRowTemplate>
</DataGrid>
```

What i'm trying to do is toggle the editable state of the `Name` column before calling the `EditCommand.Clicked`

```
private void ToggleEdit()
{
    _isEditable = !_isEditable;
}
```

```
private async void EditGridItemClick(ButtonRowContext<GridItem> context)
{
    ToggleEdit();
    await context.EditCommand.Clicked.InvokeAsync();
}
```

Selecting a row and then clicking edit button result in the following error:

```
Error: System.Collections.Generic.KeyNotFoundException: The given key '0HMSHPPT4LJMF' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Blazorise.DataGrid._DataGridRowEdit`1.<>c__DisplayClass0_0.<BuildRenderTree>b__13(RenderTreeBuilder __builder9)
   at Blazorise.Bootstrap.FieldBody.<BuildRenderTree>b__0_0(RenderTreeBuilder __builder2)
   at Microsoft.AspNetCore.Components.CascadingValue`1.Render(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

**To Reproduce**
1. Select a row of the DataGrid
2. Click on the Edit button
3. See the error

**Expected behavior**
Row edit template is displayed

Complete page code:

```
@page "/testdatagrid"

@using TestBlazorise.Entities;

<DataGrid TItem="GridItem" Data="items" Editable ShowPager>
    <DataGridColumns>
        <DataGridColumn Field="@nameof(GridItem.Id)" Caption="Id"></DataGridColumn>
        <DataGridColumn Field="@nameof(GridItem.Name)" Caption="Name" Editable="isEditable"></DataGridColumn>
    </DataGridColumns>
    <ButtonRowTemplate>
        <Button Color="Color.Primary" Clicked="@(() => EditGridItemClick(context))">
            <Icon Name="IconName.Edit" />
        </Button>
        <Button Color="Color.Danger" Clicked="@context.DeleteCommand.Clicked">
            <Icon Name="IconName.Delete" />
        </Button>
    </ButtonRowTemplate>
</DataGrid>

@code {
    private List<GridItem>? items;

    private bool isEditable { get => _isEditable; }
    private bool _isEditable = false;

    protected override void OnInitialized()
    {
        base.OnInitialized();

        items = new List<GridItem>();
        items.Add(new GridItem() { Id = 1, Name = "uno" });
        items.Add(new GridItem() { Id = 2, Name = "dos" });
        items.Add(new GridItem() { Id = 3, Name = "tres" });
        items.Add(new GridItem() { Id = 4, Name = "cuatro" });
        items.Add(new GridItem() { Id = 5, Name = "cinco" });
        items.Add(new GridItem() { Id = 6, Name = "seis" });
        items.Add(new GridItem() { Id = 7, Name = "siete" });
        items.Add(new GridItem() { Id = 8, Name = "ocho" });
        items.Add(new GridItem() { Id = 9, Name = "nueve" });
        items.Add(new GridItem() { Id = 10, Name = "diez" });
    }

    // button click
    private void ToggleEdit()
    {
        _isEditable = !_isEditable;
    }

    private async void EditGridItemClick(ButtonRowContext<GridItem> context)
    {
        ToggleEdit();
        await context.EditCommand.Clicked.InvokeAsync();
    }
}
```

**Additional context**
New project created using Blazorise with Material provider, including `Blazorise.DataGrid`

**Comment by David-Moreira** [comment]
Hello @SorioliComputec 
Is there any special reason why you are using a variable to set **Editable**?
You should be able to just use `Editable="true"`. That tells the Grid that when it's on `EditMode` it will render that field. You do not need to manually control it.


However if for some reason that's a requirement for you, here's code that should work:
(We also propose that you bind the selecteditem and check that it's not null before proceeding or disable the button if the selecteditem is null)
```
private async void EditGridItemClick( ButtonRowContext<GridItem> context )
    {
        if ( selectedItem is not null )
        {

            ToggleEdit();
            StateHasChanged();
            await Task.Yield();
            await context.EditCommand.Clicked.InvokeAsync();
        }
    }
```


Since you're mutating the row setting at the same time that you are enabling edit mode, this should avoid the race condition that was happening. 
But again I question the need for the **isEditable** field and `ToggleEdit` method.

**Comment by stsrki** [comment]
It might be even better to use `EditTemplate` on `DataGridColumn` and then render just the value instead of an input element. Depending on your use case.

**Comment by SorioliComputec** [comment]
In the example, I simplified the code; but what I need is to allow or prevent the editability of certain columns based on the cell value of the editing row. 

The solution provided by @David-Moreira works perfectly. However, following @stsrki’s advice, I only render the value when I don’t want the cell to be editable. Seems a better solution to me.

Here's an example that might help someone in the future:

```
<EditTemplate>
    @if (isSelectedRowFullyEditable)
    {
        <Validation Validator="@CheckName">
            <TextEdit Text="@((string)context.CellValue)" TextChanged="(value => context.CellValue = value)">
                <Feedback>
                    <ValidationError />
                </Feedback>
            </TextEdit>
        </Validation>
    }
    else
    {
        <Span Display="Display.Block">@context.CellValue</Span>
    }          
</EditTemplate>
```

Thanks!

**Comment by David-Moreira** [comment]
@stsrki would you think it's a common enough usage it could be worth providing a parameter to handle this for the user?
**EditableReadOnly** or something?

**Comment by stsrki** [comment]
> @stsrki would you think it's a common enough usage it could be worth providing a parameter to handle this for the user? **EditableReadOnly** or something?

I don't think it is worth doing it since it can already be done with EditTemplate.

**Comment by David-Moreira** [comment]
Closing issue, feel free to reopen if needed.
