### ISSUE TITLE
[Bug]: DataGrid Header Group breaks when none of the columns have a DisplayOrder attribute

### ISSUE THREAD

**Issue by asser-dk** [Megabit/Blazorise#5051]
### Blazorise Version

1.3.1

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction, or a simple code snippet

This is a copy of the first example from the [documentation page for datagrid header groups](https://blazorise.com/docs/extensions/datagrid/features/header-group)

The only thing I've changed is that I removed the `DisplayOrder=2` attribute from the first column in the list.

```csharp
@page "/DataGridHeaderTest"

<Heading Size="HeadingSize.Is1">DataGridHeaderTest</Heading>

<DataGrid TItem="Employee"
          Data="inMemoryData"
          ShowPager
          ShowPageSizes
          ShowHeaderGroupCaptions>
    <DataGridColumns>
        <DataGridColumn
            TItem="Employee"
            Field="@nameof(Employee.LastName)"
            HeaderGroupCaption="Personal Info"
            Caption="Last Name"/>
        <DataGridColumn
            TextAlignment="TextAlignment.Center"
            TItem="Employee"
            Field="@nameof(Employee.Id)"
            Caption="#"
            Width="60px"/>
        <DataGridColumn
            TItem="Employee"
            Field="@nameof(Employee.FirstName)"
            HeaderGroupCaption="Personal Info"
            Caption="First Name"/>
        <DataGridColumn
            TItem="Employee"
            Field="@nameof(Employee.Zip)"
            HeaderGroupCaption="Address"
            Caption="Zip"/>
        <DataGridColumn
            TItem="Employee"
            Field="@nameof(Employee.City)"
            HeaderGroupCaption="Address"
            Caption="City">
            <CaptionTemplate>
                <Icon Name="IconName.City"/>&nbsp;@context.Caption
            </CaptionTemplate>
        </DataGridColumn>
        <DataGridColumn
            TItem="Employee"
            Field="@nameof(Employee.Email)"
            HeaderGroupCaption="Personal Info"
            Caption="Email"/>
    </DataGridColumns>
</DataGrid>

@code
{
    private List<Employee> inMemoryData;

    protected override async Task OnInitializedAsync()
    {
        inMemoryData = new List<Employee>
        {
            new(1, "Samuekl", "Samuel.Collier62@gmail.com", "Collier", "91848-4714", "New Lura"),
            new(2, "Irvin", "Irvin.Ziemann@gmail.com", "Ziemann", "16505-8405", "Modestomouth"),
            new(3, "Gerald", "Gerald82@yahoo.com", "Pollich", "28612", "Theresashire"),
            new(4, "Cora", "Cora27@yahoo.com", "Conn", "10437-2253", "North Art"),
            new(5, "Alfonso", "Alfonso.DAmore@hotmail.com", "D'Amore", "87912-3933", "East Carolefort"),
            new(6, "Jessie", "Jessie_Wilkinson@gmail.com", "Wilkinson", "34306", "Mayrafurt"),
            new(7, "Gregory", "Gregory63@hotmail.com", "Renner", "57895", "West Marcelleside"),
            new(8, "Maryann", "Maryann.Hilpert12@gmail.com", "Hilpert", "38859-0368", "Boehmview"),
            new(9, "Merle22222", "Merle3@gmail.com", "Pacocha", "48154-3034", "North Erlingport"),
            new(10, "Angelina", "Angelina42@gmail.com", "Ward", "72291-1146", "Melyssaview"),
        };

        await base.OnInitializedAsync();
    }

    record Employee(int Id, string FirstName, string Email, string LastName, string Zip, string City);
}
```

### Steps to reproduce

Make a new blazor server page and paste in the code. The error should happen as soon as the page is visited.

If you add a DisplayOrder="x" where x > 0 to what seems like any or the attributes the error goes away.

Note that I did not test this on every single column, only the first 3 or so. It did not seem to matter which value I put into the DisplayOrder field as long as it was just higher than 0.

I also tried manually reordering the two first columns (so: id, firstname, email, lastname etc.) and removing the displayorder attribute but the error happened anyways.

I tried adding a header group caption to the id column as well but that also did not change anything even with or without the attribute.

I have another case where I get the same error but no matter what I do with the DisplayOrder attribute (put it on one, put it on all, a combination of either) I cannot get rid of the error. I can post that code too if needed.

### What is expected?

That I do not have to manually define the order of columns in order to group these and if I have to I would expect a nicer error message.

### What is actually happening?

* The page crashes
* Not all columns are rendered
* Some columns are duplicated when the page breaks
* The page outputs this log:

```
[14:14:45 WRN] Unhandled exception rendering component: An item with the same key has already been added. Key: 0HMU9H9UISFB6
System.ArgumentException: An item with the same key has already been added. Key: 0HMU9H9UISFB6
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Blazorise.DataGrid._BaseDataGridRow`1.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.NotifyRenderCompletedAsync()
[14:14:45 ERR] Unhandled exception in circuit 'nEH50gAkyzPReDiYok9O6_-L4cQTeei71WZI-e2tW2A'.
System.AggregateException: One or more errors occurred. (An item with the same key has already been added. Key: 0HMU9H9UISFB6)
 ---> System.ArgumentException: An item with the same key has already been added. Key: 0HMU9H9UISFB6
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Blazorise.DataGrid._BaseDataGridRow`1.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.NotifyRenderCompletedAsync()
   --- End of inner exception stack trace ---
[14:14:45 WRN] Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Blazorise.DataGrid.DataGrid`1.IsUserAgentMacintoshOS()
   at Blazorise.DataGrid.DataGrid`1.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
[14:14:45 ERR] Unhandled exception in circuit 'nEH50gAkyzPReDiYok9O6_-L4cQTeei71WZI-e2tW2A'.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Blazorise.DataGrid.DataGrid`1.IsUserAgentMacintoshOS()
   at Blazorise.DataGrid.DataGrid`1.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

### What browsers are you seeing the problem on?

Firefox

**Comment by David-Moreira** [comment]
@asser-dk Indeed a bug. Thanks for reporting.
