### ISSUE TITLE
[Bug]: Blazorise.Material JS exceptions

### ISSUE THREAD

**Issue by njannink** [Megabit/Blazorise#5276]
### Blazorise Version

1.4.2

### What Blazorise provider are you running on?

Material

### Link to minimal reproduction, or a simple code snippet

-

### Steps to reproduce

Difficult to reproduce. I believe this happens when rendering is aborted by navigating away to another page.

### What is expected?

-

### What is actually happening?

Microsoft.JSInterop.JSException: Cannot read properties of null (reading 'querySelector')
TypeError: Cannot read properties of null (reading 'querySelector')
    at Module.open (https://dev.baselinez.com/_content/Blazorise.Material/modal.js?v=1.4.2.0:7:35)
    at https://dev.baselinez.com/_framework/blazor.server.js:1:3244
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (https://dev.baselinez.com/_framework/blazor.server.js:1:3201)
    at Yt._invokeClientMethod (https://dev.baselinez.com/_framework/blazor.server.js:1:60713)
    at Yt._processIncomingData (https://dev.baselinez.com/_framework/blazor.server.js:1:58188)
    at Yt.connection.onreceive (https://dev.baselinez.com/_framework/blazor.server.js:1:51829)
    at s.onmessage (https://dev.baselinez.com/_framework/blazor.server.js:1:79974)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
   at Blazorise.Modules.BaseJSModule.InvokeSafeVoidAsync(String identifier, Object[] args)
   at Blazorise.Modal.<HandleVisibilityStyles>b__24_0()
   at Blazorise.BaseAfterRenderComponent.OnAfterRenderAsync(Boolean firstRender)
   at Blazorise.BaseComponent.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by David-Moreira** [comment]
Duplicate of #5175 ?

**Comment by David-Moreira** [comment]
> Duplicate of #5175 ?

**Edit:** While the error is not the same, it's most likely due to a js operation that was started and "aborted" by navigating away or something like that like you've said.
