### ISSUE TITLE
[Bug]: Blazorise BarItem NullReferenceException

### ISSUE THREAD

**Issue by sturlath** [Megabit/Blazorise#5406]
### Blazorise Version

1.5.0

### What Blazorise provider are you running on?

Bootstrap5

### Link to minimal reproduction or a simple code snippet

I updated my abp.io 8.0.4 to use Blazorise 1.5.0 and everything looks fine until I click the top rigtht menubar to try to log off. Then I get this error and the dreaded yellow reload banner at the bottom.

Not sure if the handling is at your end or theirs but I decided either way to report it here also since I´m going to be AFK for awaile.

```
[08:41:39 WRN] Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Blazorise.BarItem.OnDropdownVisible()
   at Blazorise.BarDropdown.SetVisibleState(Boolean visible)
   at Blazorise.BarDropdown.Toggle(String dropdownToggleElementId)
   at Blazorise.BarDropdownToggle.ClickHandler(MouseEventArgs eventArgs)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
[08:41:39 ERR] Unhandled exception in circuit '6sbqpfDqqP9xp_Z7A6ngUUWehMBr6ndciy-f7msLTCw'.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Blazorise.BarItem.OnDropdownVisible()
   at Blazorise.BarDropdown.SetVisibleState(Boolean visible)
   at Blazorise.BarDropdown.Toggle(String dropdownToggleElementId)
   at Blazorise.BarDropdownToggle.ClickHandler(MouseEventArgs eventArgs)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

### Steps to reproduce

needs abp.io

### What is expected?

no error

### What is actually happening?

error

### What browsers do you see the problem on?

Microsoft Edge

### Any additional comments?
I created an issue at abp.io also https://github.com/abpframework/abp/issues/19405

**Comment by David-Moreira** [comment]
Seems like it might stem from here : 
https://github.com/Megabit/Blazorise/pull/5344

**Comment by sturlath** [comment]
> Seems like it might stem from here :
https://github.com/Megabit/Blazorise/pull/5344

Anything I can do about it @David-Moreira ? I updated to get the indeterminate progress bar and would hate to have to revert my changes..

**Comment by David-Moreira** [comment]
Can you link the razor code for the menu?

It seems like it errors here, we'll need to null check, I think it might be a race condition when the disposal process happens since you're logging off and getting rid of the component.
![image](https://github.com/Megabit/Blazorise/assets/22283161/f6574d35-bbcf-457b-ad1f-e61b6262b138)

You might try using something like an `ErrorBoundary` temporarly around it, I suspect it will help you at least catch the error without breaking your application.

**Comment by David-Moreira** [comment]
@sturlath how easy is it for you to update blazorise with apb? Does apb need to update it or can you update it separately?

**Comment by sturlath** [comment]
@David-Moreira I can update it separatly (usually without having to wait for them to update). Do you have bits for me to try out? 🙏

**Comment by David-Moreira** [comment]
Yep I'm hoping @stsrki can do the favor of merging to master and publish our dev version for you to try it before we release 1.5 patch.

**Comment by stsrki** [comment]
Yeah, I will try to do it soon.
