### ISSUE TITLE
UnitTesting Decimal Input on DataGrid EditForm

### ISSUE THREAD

**Issue by 6030831** [Megabit/Blazorise#5865]
Hi

I'm trying to write unit test to validate the binding to my ViewModel 
I managed to simulate an edit on **input** for text field by re-using what I saw in your [TestExtensions](https://github.com/Megabit/Blazorise/blob/master/Tests/Blazorise.Tests/Extensions/TestExtensions.cs) which basically  set the the **value attribute** and then call  `input.Input(new ChangeEventArgs() { Value = fieldValue } );` (a bit strange to set value twice but it works)
I was also able to adapt that to the **select** element and it's actually simpler as just need to call `select.Change(new ChangeEventArgs() { Value = fieldValue });`.

But when I try to simulate an edit on **input** for decimal fields ie `<input inputmode="decimal" class="form-control" step="1" >`  with same method as input for string, it fails with below exception.

```
Bunit.MissingEventHandlerException
The element does not have an event handler for the event 'oninput'. It does however have event handlers for these events, 'onkeydown', 'onkeypress', 'onkeyup', 'onblur', 'onfocus', 'onfocusin', 'onfocusout'.
   at Bunit.TriggerEventDispatchExtensions.TriggerBubblingEventAsync(ITestRenderer renderer, IElement element, String eventName, EventArgs eventArgs) in /_/src/bunit.web/EventDispatchExtensions/TriggerEventDispatchExtensions.cs:line 121
   at Bunit.TriggerEventDispatchExtensions.TriggerEventsAsync(ITestRenderer renderer, IElement element, String eventName, EventArgs eventArgs) in /_/src/bunit.web/EventDispatchExtensions/TriggerEventDispatchExtensions.cs:line 93
   at Bunit.TriggerEventDispatchExtensions.<>c__DisplayClass3_0.<TriggerEventAsync>b__0() in /_/src/bunit.web/EventDispatchExtensions/TriggerEventDispatchExtensions.cs:line 80
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<<InvokeAsync>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Bunit.TriggerEventDispatchExtensions.ThrowIfFailedSynchronously(Task result) in /_/src/bunit.web/EventDispatchExtensions/TriggerEventDispatchExtensions.cs:line 215
   at Bunit.TriggerEventDispatchExtensions.TriggerEventAsync(IElement element, String eventName, EventArgs eventArgs) in /_/src/bunit.web/EventDispatchExtensions/TriggerEventDispatchExtensions.cs:line 82
   at Bunit.InputEventDispatchExtensions.InputAsync(IElement element, ChangeEventArgs eventArgs) in /_/src/bunit.web/EventDispatchExtensions/InputEventDispatchExtensions.cs:line 78
```

When I check the input element with debugger (AngleSharp.Dom.IElement {Bunit.Web.AngleSharp.HtmlInputElementWrapper)  this is what I see and indeed no handler 
`
input = <input id="0HN89PEN279L1" inputmode="decimal" class="form-control" step="1" blazor:onkeydown="499" blazor:onkeypress="500" blazor:onkeyup="501" blazor:onblur="502" blazor:onfocus="503" blazor:onfocusin="504" blazor:onfocusout="505" blazor:elementreference="">
`

Any idea on how to achieve that ?

**Comment by stsrki** [comment]
I suspect that NumericPicker is used behind the scenes. The NumericPicker is mainly handled by the JS because it needs to take care of decimal separators, formating, etc. So it can be that it uses different events, possibly `onchange`.

In case you want to switch back to NumericEdit for DataGrid, you can set the `NativeInputMode`.

eg

`<DataGridNumericColumn NativeInputMode />`
